version: "3.4"

services:
  frontend:
    image: soliddesk/admin-frontend
    build: 
      context: .
      target: frontend
    volumes:
      - .:/var/www
  backend:
    image: soliddesk/backend
    build: 
      context: .
      target: backend
    volumes:
      - .:/var/www
      - /srv/share/composer-cache:/root/.composer/cache
  app:
    image: soliddesk/admin
    build: .
    volumes:
      - .:/var/www
    ports:
      - 80:80
  ci-test:
    image: soliddesk/admin
    volumes:
      - ./vendor:/var/www/vendor
