version: "3.4"

services:
  frontend:
    image: solid/admin/frontend
    build: 
      context: .
      target: frontend
    volumes:
      - .:/var/www
  backend:
    image: solid/admin/backend
    build: 
      context: .
      target: backend
    volumes:
      - .:/var/www
      - /home/composer-cache:/root/.composer/cache
      - /dev/null:/usr/local/etc/php/conf.d/opcache.ini
  app:
    image: solid/admin
    build: .
    volumes:
      - .:/var/www
      - /dev/null:/usr/local/etc/php/conf.d/opcache.ini
    ports:
      - 80:80
    depends_on:
      - database
  database:
    image: mysql:5.6
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: soliddesk
